const SET_LOADING = 'SET_LOADING';
const SET_STORİES = 'SET_STORİES';
const REMOVE_STORY = 'REMOVE_STORY';
const HANDLE_PAGE = 'HANDLE_PAGE';
const HANDLE_SEARCH = 'HANDLE_SEARCH';

export { SET_LOADING, SET_STORİES, REMOVE_STORY, HANDLE_PAGE, HANDLE_SEARCH };
